#!/bin/sh
#注册准备
pkg add /usr/local/sbin/packages/liblz4-1.9.4,1.pkg
pkg add /usr/local/sbin/packages/gmp-6.2.1.pkg
pkg add /usr/local/sbin/packages/zstd-1.5.5.pkg
pkg add /usr/local/sbin/packages/mpfr-4.2.0_1,1.pkg
pkg add /usr/local/sbin/packages/mpc-1.3.1_1.pkg
pkg add /usr/local/sbin/packages/binutils-2.40_4,1.pkg
pkg add /usr/local/sbin/packages/gcc12-12.2.0_6.pkg
pkg add /usr/local/sbin/packages/gcc-12_5.pkg
#建立入侵检测初始化库
mkdir -p /usr/local/etc/suricata/pfwsense.rules/
\cp /usr/local/sbin/pfwsense.rules/* /usr/local/etc/suricata/pfwsense.rules/
\cp /usr/local/sbin/rules/* /usr/local/etc/suricata/rules/
#安装插件