#!/bin/sh
path=$1
filename=$2
newfilename=$3
echo "We are finding '$filename' under the folder '$path'"
count=1
for i in `find $path -name "*$filename*" | tail -r`
do
    newpath=`echo $i | sed "s@\(.*\)$filename@\1$newfilename@"`
    mv "$i" "$newpath"
    echo "${count}: Renaming $i to $newpath"
    count=$(($count+1))
done
